#! /usr/bin/env bash

# This variable needs to exist
prefix=/home/csamaner/MG5_aMC_v2_3_3/pythia-pgs/libraries/lhapdf

if [[ -n $( echo $* | egrep -- "--help|-h" ) ]]; then
    echo "lhapdf-config: configuration tool for the LHAPDF"
    echo "               parton density function evolution library"
    echo "               http://durpdg.dur.ac.uk/lhapdf/"
    echo
    echo "Usage: lhapdf-config [[--help|-h] | [--prefix] | [--pdfsets-path]]"
    echo "Options:"
    echo "  --help | -h   : show this help message"
    echo "  --prefix      : show the installation prefix (cf. autoconf)"
    echo "  --pdfsets-path : show the path to the directory containing the PDF set data files"
    echo
fi

if [[ -n $( echo $* | egrep -- --prefix ) ]]; then
    echo $prefix
fi

if [[ -n $( echo $* | egrep -- --pdfsets-path ) ]]; then
    echo /home/csamaner/MG5_aMC_v2_3_3/pythia-pgs/src/lhapdf/PDFsets
fi
