      SUBROUTINE SMATRIX1(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.3.2, 2018-06-22
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > g g g WEIGHTED<=3 @1
C     
      USE DISCRETESAMPLER
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=45)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=25)
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     global (due to reading writting) 
C     
      LOGICAL GOODHEL(NCOMB,2)
      INTEGER NTRY(2)
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      INTEGER ISHEL(2)
      REAL*8 T,MATRIX1
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER NGOOD(2), IGOOD(NCOMB,2)
      INTEGER JHEL(2), J, JJ
      INTEGER THIS_NTRY(2)
      SAVE THIS_NTRY
      DATA THIS_NTRY /0,0/
C     This is just to temporarily store the reference grid for
C      helicity of the DiscreteSampler so as to obtain its number of
C      entries with ref_helicity_grid%n_tot_entries
      TYPE(SAMPLEDDIMENSION) REF_HELICITY_GRID
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2

      CHARACTER*101         HEL_BUFF
      COMMON/TO_HELICITY/  HEL_BUFF

      INTEGER IMIRROR
      COMMON/TO_MIRROR/ IMIRROR

      REAL*8 POL(2)
      COMMON/TO_POLARIZATION/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      DATA XTRY, XREJ /0,0/
      DATA NGOOD /0,0/
      DATA ISHEL/0,0/
      SAVE YFRAC, IGOOD, JHEL
      DATA (NHEL(I,   1),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,5) / 1, 1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,5) / 1, 1, 1, 1, 1/
      DATA IDEN/1536/

C     To be able to control when the matrix<i> subroutine can add
C      entries to the grid for the MC over helicity configuration
      LOGICAL ALLOW_HELICITY_GRID_ENTRIES
      COMMON/TO_ALLOW_HELICITY_GRID_ENTRIES/ALLOW_HELICITY_GRID_ENTRIES

C     ----------
C     BEGIN CODE
C     ----------
      NTRY(IMIRROR)=NTRY(IMIRROR)+1
      THIS_NTRY(IMIRROR) = THIS_NTRY(IMIRROR)+1
      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
        JAMP2(0)=24
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
      ENDIF
      ANS = 0D0
      WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL)
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO

        !   If the helicity grid status is 0, this means that it is not yet initialized.
        !   If HEL_PICKED==-1, this means that calls to other matrix<i> where in initialization mode as well for the helicity.
      IF ((ISHEL(IMIRROR).EQ.0.AND.ISUM_HEL.EQ.0).OR.(DS_GET_DIM_STATUS
     $('Helicity').EQ.0).OR.(HEL_PICKED.EQ.-1)) THEN
        DO I=1,NCOMB
          IF (GOODHEL(I,IMIRROR) .OR. NTRY(IMIRROR).LE.MAXTRIES.OR.(ISU
     $M_HEL.NE.0).OR.THIS_NTRY(IMIRROR).LE.2) THEN
            T=MATRIX1(P ,NHEL(1,I),JC(1))
            DO JJ=1,NINCOMING
              IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))
     $         )) THEN
                T=T*ABS(POL(JJ))
              ELSE IF(POL(JJ).NE.1D0)THEN
                T=T*(2D0-ABS(POL(JJ)))
              ENDIF
            ENDDO
            IF (ISUM_HEL.NE.0.AND.DS_GET_DIM_STATUS('Helicity')
     $       .EQ.0.AND.ALLOW_HELICITY_GRID_ENTRIES) THEN
              CALL DS_ADD_ENTRY('Helicity',I,T)
            ENDIF
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        IF(NTRY(IMIRROR).EQ.(MAXTRIES+1)) THEN
          CALL RESET_CUMULATIVE_VARIABLE()  ! avoid biais of the initialization
        ENDIF
        IF (ISUM_HEL.NE.0) THEN
            !         We set HEL_PICKED to -1 here so that later on, the call to DS_add_point in dsample.f does not add anything to the grid since it was already done here.
          HEL_PICKED = -1
            !         For safety, hardset the helicity sampling jacobian to 0.0d0 to make sure it is not .
          HEL_JACOBIAN   = 1.0D0
            !         We don't want to re-update the helicity grid if it was already updated by another matrix<i>, so we make sure that the reference grid is empty.
          REF_HELICITY_GRID = DS_GET_DIMENSION(REF_GRID,'Helicity')
          IF((DS_GET_DIM_STATUS('Helicity').EQ.1).AND.(REF_HELICITY_GRI
     $D%N_TOT_ENTRIES.EQ.0)) THEN
              !           If we finished the initialization we can update the grid so as to start sampling over it.
              !           However the grid will now be filled by dsample with different kind of weights (including pdf, flux, etc...) so by setting the grid_mode of the reference grid to 'initialization' we make sure it will be overwritten (as opposed to 'combined') by the running grid at the next update.
            CALL DS_UPDATE_GRID('Helicity')
            CALL DS_SET_GRID_MODE('Helicity','init')
          ENDIF
        ELSE
          JHEL(IMIRROR) = 1
          IF(NTRY(IMIRROR).LE.MAXTRIES.OR.THIS_NTRY(IMIRROR).LE.2)THEN
            DO I=1,NCOMB
              IF (.NOT.GOODHEL(I,IMIRROR) .AND. (DABS(TS(I)).GT.ANS
     $         *LIMHEL/NCOMB)) THEN
                GOODHEL(I,IMIRROR)=.TRUE.
                NGOOD(IMIRROR) = NGOOD(IMIRROR) +1
                IGOOD(NGOOD(IMIRROR),IMIRROR) = I
                PRINT *,'Added good helicity ',I,TS(I)*NCOMB/ANS,' in'
     $           //' event ',NTRY(IMIRROR), 'local:',THIS_NTRY(IMIRROR)
              ENDIF
            ENDDO
          ENDIF
          IF(NTRY(IMIRROR).EQ.MAXTRIES)THEN
            ISHEL(IMIRROR)=MIN(ISUM_HEL,NGOOD(IMIRROR))
          ENDIF
        ENDIF
      ELSE  ! random helicity 
C       The helicity configuration was chosen already by genps and put
C        in a common block defined in genps.inc.
        I = HEL_PICKED

        T=MATRIX1(P ,NHEL(1,I),JC(1))

        DO JJ=1,NINCOMING
          IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))
          ELSE IF(POL(JJ).NE.1D0)THEN
            T=T*(2D0-ABS(POL(JJ)))
          ENDIF
        ENDDO
C       Always one helicity at a time
        ANS = T
C       Include the Jacobian from helicity sampling
        ANS = ANS * HEL_JACOBIAN

        WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
      ENDIF
      IF (ANS.NE.0D0.AND.(ISUM_HEL .NE. 1.OR.HEL_PICKED.EQ.-1)) THEN
        CALL RANMAR(R)
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(R.LT.SUMHEL)THEN
            WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(1))/XTOT
        ELSE IF(ANS.NE.0D0) THEN
          WRITE(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          STOP 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX1(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.3.2, 2018-06-22
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > g g g WEIGHTED<=3 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=45)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=12, NCOLOR=24)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/108/
      DATA (CF(I,  1),I=  1,  6) /  455,  -58,  -58,   14,   14,   68/
      DATA (CF(I,  1),I=  7, 12) /  -58,   -4,   14,  -58,    5,   -4/
      DATA (CF(I,  1),I= 13, 18) /   14,    5,   68,   -4,   14,   68/
      DATA (CF(I,  1),I= 19, 24) /  -58,   -4,   -4,   68,   68,  -40/
C     1 Tr(1,2,3,4,5)
      DATA DENOM(2)/108/
      DATA (CF(I,  2),I=  1,  6) /  -58,  455,   14,   68,  -58,   14/
      DATA (CF(I,  2),I=  7, 12) /   -4,  -58,    5,   -4,   14,  -58/
      DATA (CF(I,  2),I= 13, 18) /  -58,   -4,   -4,   68,   68,  -40/
      DATA (CF(I,  2),I= 19, 24) /   14,    5,   68,   -4,   14,   68/
C     1 Tr(1,2,3,5,4)
      DATA DENOM(3)/108/
      DATA (CF(I,  3),I=  1,  6) /  -58,   14,  455,  -58,   68,   14/
      DATA (CF(I,  3),I=  7, 12) /   14,    5,   68,   -4,   14,   68/
      DATA (CF(I,  3),I= 13, 18) /  -58,   -4,   14,  -58,    5,   -4/
      DATA (CF(I,  3),I= 19, 24) /   -4,  -58,   68,  -40,   -4,   68/
C     1 Tr(1,2,4,3,5)
      DATA DENOM(4)/108/
      DATA (CF(I,  4),I=  1,  6) /   14,   68,  -58,  455,   14,  -58/
      DATA (CF(I,  4),I=  7, 12) /  -58,   -4,   -4,   68,   68,  -40/
      DATA (CF(I,  4),I= 13, 18) /   -4,  -58,    5,   -4,   14,  -58/
      DATA (CF(I,  4),I= 19, 24) /    5,   14,   14,   68,   68,   -4/
C     1 Tr(1,2,4,5,3)
      DATA DENOM(5)/108/
      DATA (CF(I,  5),I=  1,  6) /   14,  -58,   68,   14,  455,  -58/
      DATA (CF(I,  5),I=  7, 12) /    5,   14,   14,   68,   68,   -4/
      DATA (CF(I,  5),I= 13, 18) /   -4,  -58,   68,  -40,   -4,   68/
      DATA (CF(I,  5),I= 19, 24) /  -58,   -4,   14,  -58,    5,   -4/
C     1 Tr(1,2,5,3,4)
      DATA DENOM(6)/108/
      DATA (CF(I,  6),I=  1,  6) /   68,   14,   14,  -58,  -58,  455/
      DATA (CF(I,  6),I=  7, 12) /   -4,  -58,   68,  -40,   -4,   68/
      DATA (CF(I,  6),I= 13, 18) /    5,   14,   14,   68,   68,   -4/
      DATA (CF(I,  6),I= 19, 24) /   -4,  -58,    5,   -4,   14,  -58/
C     1 Tr(1,2,5,4,3)
      DATA DENOM(7)/108/
      DATA (CF(I,  7),I=  1,  6) /  -58,   -4,   14,  -58,    5,   -4/
      DATA (CF(I,  7),I=  7, 12) /  455,  -58,  -58,   14,   14,   68/
      DATA (CF(I,  7),I= 13, 18) /   68,   -4,   14,    5,   68,   14/
      DATA (CF(I,  7),I= 19, 24) /   -4,   68,  -58,   -4,  -40,   68/
C     1 Tr(1,3,2,4,5)
      DATA DENOM(8)/108/
      DATA (CF(I,  8),I=  1,  6) /   -4,  -58,    5,   -4,   14,  -58/
      DATA (CF(I,  8),I=  7, 12) /  -58,  455,   14,   68,  -58,   14/
      DATA (CF(I,  8),I= 13, 18) /   -4,   68,  -58,   -4,  -40,   68/
      DATA (CF(I,  8),I= 19, 24) /   68,   -4,   14,    5,   68,   14/
C     1 Tr(1,3,2,5,4)
      DATA DENOM(9)/108/
      DATA (CF(I,  9),I=  1,  6) /   14,    5,   68,   -4,   14,   68/
      DATA (CF(I,  9),I=  7, 12) /  -58,   14,  455,  -58,   68,   14/
      DATA (CF(I,  9),I= 13, 18) /   14,  -58,  -58,   -4,   -4,    5/
      DATA (CF(I,  9),I= 19, 24) /   68,  -40,   -4,  -58,   68,   -4/
C     1 Tr(1,3,4,2,5)
      DATA DENOM(10)/108/
      DATA (CF(I, 10),I=  1,  6) /  -58,   -4,   -4,   68,   68,  -40/
      DATA (CF(I, 10),I=  7, 12) /   14,   68,  -58,  455,   14,  -58/
      DATA (CF(I, 10),I= 13, 18) /    5,   -4,   -4,  -58,  -58,   14/
      DATA (CF(I, 10),I= 19, 24) /   14,   68,    5,   14,   -4,   68/
C     1 Tr(1,3,4,5,2)
      DATA DENOM(11)/108/
      DATA (CF(I, 11),I=  1,  6) /    5,   14,   14,   68,   68,   -4/
      DATA (CF(I, 11),I=  7, 12) /   14,  -58,   68,   14,  455,  -58/
      DATA (CF(I, 11),I= 13, 18) /   68,  -40,   -4,  -58,   68,   -4/
      DATA (CF(I, 11),I= 19, 24) /   14,  -58,  -58,   -4,   -4,    5/
C     1 Tr(1,3,5,2,4)
      DATA DENOM(12)/108/
      DATA (CF(I, 12),I=  1,  6) /   -4,  -58,   68,  -40,   -4,   68/
      DATA (CF(I, 12),I=  7, 12) /   68,   14,   14,  -58,  -58,  455/
      DATA (CF(I, 12),I= 13, 18) /   14,   68,    5,   14,   -4,   68/
      DATA (CF(I, 12),I= 19, 24) /    5,   -4,   -4,  -58,  -58,   14/
C     1 Tr(1,3,5,4,2)
      DATA DENOM(13)/108/
      DATA (CF(I, 13),I=  1,  6) /   14,  -58,  -58,   -4,   -4,    5/
      DATA (CF(I, 13),I=  7, 12) /   68,   -4,   14,    5,   68,   14/
      DATA (CF(I, 13),I= 13, 18) /  455,  -58,  -58,   14,   14,   68/
      DATA (CF(I, 13),I= 19, 24) /   68,   -4,  -40,   68,  -58,   -4/
C     1 Tr(1,4,2,3,5)
      DATA DENOM(14)/108/
      DATA (CF(I, 14),I=  1,  6) /    5,   -4,   -4,  -58,  -58,   14/
      DATA (CF(I, 14),I=  7, 12) /   -4,   68,  -58,   -4,  -40,   68/
      DATA (CF(I, 14),I= 13, 18) /  -58,  455,   14,   68,  -58,   14/
      DATA (CF(I, 14),I= 19, 24) /   -4,   68,   68,   14,   14,    5/
C     1 Tr(1,4,2,5,3)
      DATA DENOM(15)/108/
      DATA (CF(I, 15),I=  1,  6) /   68,   -4,   14,    5,   68,   14/
      DATA (CF(I, 15),I=  7, 12) /   14,  -58,  -58,   -4,   -4,    5/
      DATA (CF(I, 15),I= 13, 18) /  -58,   14,  455,  -58,   68,   14/
      DATA (CF(I, 15),I= 19, 24) /  -40,   68,   68,   -4,   -4,  -58/
C     1 Tr(1,4,3,2,5)
      DATA DENOM(16)/108/
      DATA (CF(I, 16),I=  1,  6) /   -4,   68,  -58,   -4,  -40,   68/
      DATA (CF(I, 16),I=  7, 12) /    5,   -4,   -4,  -58,  -58,   14/
      DATA (CF(I, 16),I= 13, 18) /   14,   68,  -58,  455,   14,  -58/
      DATA (CF(I, 16),I= 19, 24) /   68,   14,   -4,   68,    5,   14/
C     1 Tr(1,4,3,5,2)
      DATA DENOM(17)/108/
      DATA (CF(I, 17),I=  1,  6) /   14,   68,    5,   14,   -4,   68/
      DATA (CF(I, 17),I=  7, 12) /   68,  -40,   -4,  -58,   68,   -4/
      DATA (CF(I, 17),I= 13, 18) /   14,  -58,   68,   14,  455,  -58/
      DATA (CF(I, 17),I= 19, 24) /  -58,   14,   -4,    5,  -58,   -4/
C     1 Tr(1,4,5,2,3)
      DATA DENOM(18)/108/
      DATA (CF(I, 18),I=  1,  6) /   68,  -40,   -4,  -58,   68,   -4/
      DATA (CF(I, 18),I=  7, 12) /   14,   68,    5,   14,   -4,   68/
      DATA (CF(I, 18),I= 13, 18) /   68,   14,   14,  -58,  -58,  455/
      DATA (CF(I, 18),I= 19, 24) /   -4,    5,  -58,   14,   -4,  -58/
C     1 Tr(1,4,5,3,2)
      DATA DENOM(19)/108/
      DATA (CF(I, 19),I=  1,  6) /  -58,   14,   -4,    5,  -58,   -4/
      DATA (CF(I, 19),I=  7, 12) /   -4,   68,   68,   14,   14,    5/
      DATA (CF(I, 19),I= 13, 18) /   68,   -4,  -40,   68,  -58,   -4/
      DATA (CF(I, 19),I= 19, 24) /  455,  -58,  -58,   14,   14,   68/
C     1 Tr(1,5,2,3,4)
      DATA DENOM(20)/108/
      DATA (CF(I, 20),I=  1,  6) /   -4,    5,  -58,   14,   -4,  -58/
      DATA (CF(I, 20),I=  7, 12) /   68,   -4,  -40,   68,  -58,   -4/
      DATA (CF(I, 20),I= 13, 18) /   -4,   68,   68,   14,   14,    5/
      DATA (CF(I, 20),I= 19, 24) /  -58,  455,   14,   68,  -58,   14/
C     1 Tr(1,5,2,4,3)
      DATA DENOM(21)/108/
      DATA (CF(I, 21),I=  1,  6) /   -4,   68,   68,   14,   14,    5/
      DATA (CF(I, 21),I=  7, 12) /  -58,   14,   -4,    5,  -58,   -4/
      DATA (CF(I, 21),I= 13, 18) /  -40,   68,   68,   -4,   -4,  -58/
      DATA (CF(I, 21),I= 19, 24) /  -58,   14,  455,  -58,   68,   14/
C     1 Tr(1,5,3,2,4)
      DATA DENOM(22)/108/
      DATA (CF(I, 22),I=  1,  6) /   68,   -4,  -40,   68,  -58,   -4/
      DATA (CF(I, 22),I=  7, 12) /   -4,    5,  -58,   14,   -4,  -58/
      DATA (CF(I, 22),I= 13, 18) /   68,   14,   -4,   68,    5,   14/
      DATA (CF(I, 22),I= 19, 24) /   14,   68,  -58,  455,   14,  -58/
C     1 Tr(1,5,3,4,2)
      DATA DENOM(23)/108/
      DATA (CF(I, 23),I=  1,  6) /   68,   14,   -4,   68,    5,   14/
      DATA (CF(I, 23),I=  7, 12) /  -40,   68,   68,   -4,   -4,  -58/
      DATA (CF(I, 23),I= 13, 18) /  -58,   14,   -4,    5,  -58,   -4/
      DATA (CF(I, 23),I= 19, 24) /   14,  -58,   68,   14,  455,  -58/
C     1 Tr(1,5,4,2,3)
      DATA DENOM(24)/108/
      DATA (CF(I, 24),I=  1,  6) /  -40,   68,   68,   -4,   -4,  -58/
      DATA (CF(I, 24),I=  7, 12) /   68,   14,   -4,   68,    5,   14/
      DATA (CF(I, 24),I= 13, 18) /   -4,    5,  -58,   14,   -4,  -58/
      DATA (CF(I, 24),I= 19, 24) /   68,   14,   14,  -58,  -58,  455/
C     1 Tr(1,5,4,3,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL VXXXXX(P(0,3),ZERO,NHEL(3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL VXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_10,ZERO,ZERO,W(1,6))
      CALL VVV1P0_1(W(1,3),W(1,4),GC_10,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL VVV1_0(W(1,6),W(1,7),W(1,5),GC_10,AMP(1))
      CALL VVV1P0_1(W(1,3),W(1,5),GC_10,ZERO,ZERO,W(1,8))
C     Amplitude(s) for diagram number 2
      CALL VVV1_0(W(1,6),W(1,8),W(1,4),GC_10,AMP(2))
      CALL VVV1P0_1(W(1,4),W(1,5),GC_10,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,6),W(1,3),W(1,9),GC_10,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL VVVV1_0(W(1,3),W(1,4),W(1,5),W(1,6),GC_12,AMP(4))
      CALL VVVV3_0(W(1,3),W(1,4),W(1,5),W(1,6),GC_12,AMP(5))
      CALL VVVV4_0(W(1,3),W(1,4),W(1,5),W(1,6),GC_12,AMP(6))
      CALL VVV1P0_1(W(1,1),W(1,3),GC_10,ZERO,ZERO,W(1,6))
      CALL VVV1P0_1(W(1,2),W(1,4),GC_10,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 5
      CALL VVV1_0(W(1,6),W(1,10),W(1,5),GC_10,AMP(7))
      CALL VVV1P0_1(W(1,2),W(1,5),GC_10,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 6
      CALL VVV1_0(W(1,6),W(1,11),W(1,4),GC_10,AMP(8))
C     Amplitude(s) for diagram number 7
      CALL VVV1_0(W(1,6),W(1,2),W(1,9),GC_10,AMP(9))
C     Amplitude(s) for diagram number 8
      CALL VVVV1_0(W(1,2),W(1,4),W(1,5),W(1,6),GC_12,AMP(10))
      CALL VVVV3_0(W(1,2),W(1,4),W(1,5),W(1,6),GC_12,AMP(11))
      CALL VVVV4_0(W(1,2),W(1,4),W(1,5),W(1,6),GC_12,AMP(12))
      CALL VVV1P0_1(W(1,1),W(1,4),GC_10,ZERO,ZERO,W(1,6))
      CALL VVV1P0_1(W(1,2),W(1,3),GC_10,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 9
      CALL VVV1_0(W(1,6),W(1,12),W(1,5),GC_10,AMP(13))
C     Amplitude(s) for diagram number 10
      CALL VVV1_0(W(1,6),W(1,11),W(1,3),GC_10,AMP(14))
C     Amplitude(s) for diagram number 11
      CALL VVV1_0(W(1,6),W(1,2),W(1,8),GC_10,AMP(15))
C     Amplitude(s) for diagram number 12
      CALL VVVV1_0(W(1,2),W(1,3),W(1,5),W(1,6),GC_12,AMP(16))
      CALL VVVV3_0(W(1,2),W(1,3),W(1,5),W(1,6),GC_12,AMP(17))
      CALL VVVV4_0(W(1,2),W(1,3),W(1,5),W(1,6),GC_12,AMP(18))
      CALL VVV1P0_1(W(1,1),W(1,5),GC_10,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 13
      CALL VVV1_0(W(1,6),W(1,12),W(1,4),GC_10,AMP(19))
C     Amplitude(s) for diagram number 14
      CALL VVV1_0(W(1,6),W(1,10),W(1,3),GC_10,AMP(20))
C     Amplitude(s) for diagram number 15
      CALL VVV1_0(W(1,6),W(1,2),W(1,7),GC_10,AMP(21))
C     Amplitude(s) for diagram number 16
      CALL VVVV1_0(W(1,2),W(1,3),W(1,4),W(1,6),GC_12,AMP(22))
      CALL VVVV3_0(W(1,2),W(1,3),W(1,4),W(1,6),GC_12,AMP(23))
      CALL VVVV4_0(W(1,2),W(1,3),W(1,4),W(1,6),GC_12,AMP(24))
C     Amplitude(s) for diagram number 17
      CALL VVV1_0(W(1,1),W(1,12),W(1,9),GC_10,AMP(25))
C     Amplitude(s) for diagram number 18
      CALL VVV1_0(W(1,1),W(1,10),W(1,8),GC_10,AMP(26))
C     Amplitude(s) for diagram number 19
      CALL VVV1_0(W(1,1),W(1,11),W(1,7),GC_10,AMP(27))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,3),GC_12,ZERO,ZERO,W(1,11))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,3),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,3),GC_12,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 20
      CALL VVV1_0(W(1,4),W(1,5),W(1,11),GC_10,AMP(28))
      CALL VVV1_0(W(1,4),W(1,5),W(1,7),GC_10,AMP(29))
      CALL VVV1_0(W(1,4),W(1,5),W(1,10),GC_10,AMP(30))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,4),GC_12,ZERO,ZERO,W(1,10))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,4),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,4),GC_12,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 21
      CALL VVV1_0(W(1,3),W(1,5),W(1,10),GC_10,AMP(31))
      CALL VVV1_0(W(1,3),W(1,5),W(1,7),GC_10,AMP(32))
      CALL VVV1_0(W(1,3),W(1,5),W(1,11),GC_10,AMP(33))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,5),GC_12,ZERO,ZERO,W(1,11))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,5),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,5),GC_12,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 22
      CALL VVV1_0(W(1,3),W(1,4),W(1,11),GC_10,AMP(34))
      CALL VVV1_0(W(1,3),W(1,4),W(1,7),GC_10,AMP(35))
      CALL VVV1_0(W(1,3),W(1,4),W(1,10),GC_10,AMP(36))
      CALL VVVV1P0_1(W(1,1),W(1,3),W(1,4),GC_12,ZERO,ZERO,W(1,10))
      CALL VVVV3P0_1(W(1,1),W(1,3),W(1,4),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,3),W(1,4),GC_12,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 23
      CALL VVV1_0(W(1,2),W(1,5),W(1,10),GC_10,AMP(37))
      CALL VVV1_0(W(1,2),W(1,5),W(1,7),GC_10,AMP(38))
      CALL VVV1_0(W(1,2),W(1,5),W(1,11),GC_10,AMP(39))
      CALL VVVV1P0_1(W(1,1),W(1,3),W(1,5),GC_12,ZERO,ZERO,W(1,11))
      CALL VVVV3P0_1(W(1,1),W(1,3),W(1,5),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,3),W(1,5),GC_12,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 24
      CALL VVV1_0(W(1,2),W(1,4),W(1,11),GC_10,AMP(40))
      CALL VVV1_0(W(1,2),W(1,4),W(1,7),GC_10,AMP(41))
      CALL VVV1_0(W(1,2),W(1,4),W(1,10),GC_10,AMP(42))
      CALL VVVV1P0_1(W(1,1),W(1,4),W(1,5),GC_12,ZERO,ZERO,W(1,10))
      CALL VVVV3P0_1(W(1,1),W(1,4),W(1,5),GC_12,ZERO,ZERO,W(1,7))
      CALL VVVV4P0_1(W(1,1),W(1,4),W(1,5),GC_12,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 25
      CALL VVV1_0(W(1,2),W(1,3),W(1,10),GC_10,AMP(43))
      CALL VVV1_0(W(1,2),W(1,3),W(1,7),GC_10,AMP(44))
      CALL VVV1_0(W(1,2),W(1,3),W(1,11),GC_10,AMP(45))
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1)=+2D0*(+IMAG1*AMP(1)+IMAG1*AMP(3)+IMAG1*AMP(4)-IMAG1
     $ *AMP(6)-IMAG1*AMP(19)-IMAG1*AMP(21)-IMAG1*AMP(22)+IMAG1*AMP(24)
     $ +IMAG1*AMP(25)-IMAG1*AMP(30)+IMAG1*AMP(28)+IMAG1*AMP(36)+IMAG1
     $ *AMP(35)-IMAG1*AMP(44)-IMAG1*AMP(43))
      JAMP(2,1)=+2D0*(+IMAG1*AMP(2)-IMAG1*AMP(3)+IMAG1*AMP(5)+IMAG1
     $ *AMP(6)-IMAG1*AMP(13)-IMAG1*AMP(15)-IMAG1*AMP(16)+IMAG1*AMP(18)
     $ -IMAG1*AMP(25)+IMAG1*AMP(30)-IMAG1*AMP(28)+IMAG1*AMP(33)+IMAG1
     $ *AMP(32)-IMAG1*AMP(45)+IMAG1*AMP(43))
      JAMP(3,1)=+2D0*(-IMAG1*AMP(1)-IMAG1*AMP(2)-IMAG1*AMP(5)-IMAG1
     $ *AMP(4)-IMAG1*AMP(20)+IMAG1*AMP(21)-IMAG1*AMP(23)-IMAG1*AMP(24)
     $ +IMAG1*AMP(26)-IMAG1*AMP(33)+IMAG1*AMP(31)-IMAG1*AMP(36)-IMAG1
     $ *AMP(35)-IMAG1*AMP(41)-IMAG1*AMP(40))
      JAMP(4,1)=+2D0*(+IMAG1*AMP(2)-IMAG1*AMP(3)+IMAG1*AMP(5)+IMAG1
     $ *AMP(6)-IMAG1*AMP(7)-IMAG1*AMP(9)-IMAG1*AMP(10)+IMAG1*AMP(12)
     $ -IMAG1*AMP(26)+IMAG1*AMP(30)+IMAG1*AMP(29)+IMAG1*AMP(33)-IMAG1
     $ *AMP(31)-IMAG1*AMP(42)+IMAG1*AMP(40))
      JAMP(5,1)=+2D0*(-IMAG1*AMP(1)-IMAG1*AMP(2)-IMAG1*AMP(5)-IMAG1
     $ *AMP(4)-IMAG1*AMP(14)+IMAG1*AMP(15)-IMAG1*AMP(17)-IMAG1*AMP(18)
     $ +IMAG1*AMP(27)-IMAG1*AMP(33)-IMAG1*AMP(32)-IMAG1*AMP(36)+IMAG1
     $ *AMP(34)-IMAG1*AMP(38)-IMAG1*AMP(37))
      JAMP(6,1)=+2D0*(+IMAG1*AMP(1)+IMAG1*AMP(3)+IMAG1*AMP(4)-IMAG1
     $ *AMP(6)-IMAG1*AMP(8)+IMAG1*AMP(9)-IMAG1*AMP(11)-IMAG1*AMP(12)
     $ -IMAG1*AMP(27)-IMAG1*AMP(30)-IMAG1*AMP(29)+IMAG1*AMP(36)-IMAG1
     $ *AMP(34)-IMAG1*AMP(39)+IMAG1*AMP(37))
      JAMP(7,1)=+2D0*(+IMAG1*AMP(7)+IMAG1*AMP(9)+IMAG1*AMP(10)-IMAG1
     $ *AMP(12)+IMAG1*AMP(19)+IMAG1*AMP(20)+IMAG1*AMP(23)+IMAG1*AMP(22)
     $ -IMAG1*AMP(25)-IMAG1*AMP(29)-IMAG1*AMP(28)+IMAG1*AMP(42)+IMAG1
     $ *AMP(41)+IMAG1*AMP(44)+IMAG1*AMP(43))
      JAMP(8,1)=+2D0*(+IMAG1*AMP(8)-IMAG1*AMP(9)+IMAG1*AMP(11)+IMAG1
     $ *AMP(12)+IMAG1*AMP(13)+IMAG1*AMP(14)+IMAG1*AMP(17)+IMAG1*AMP(16)
     $ +IMAG1*AMP(25)+IMAG1*AMP(29)+IMAG1*AMP(28)+IMAG1*AMP(39)+IMAG1
     $ *AMP(38)+IMAG1*AMP(45)-IMAG1*AMP(43))
      JAMP(9,1)=+2D0*(-IMAG1*AMP(7)-IMAG1*AMP(8)-IMAG1*AMP(11)-IMAG1
     $ *AMP(10)-IMAG1*AMP(20)+IMAG1*AMP(21)-IMAG1*AMP(23)-IMAG1*AMP(24)
     $ -IMAG1*AMP(27)-IMAG1*AMP(35)-IMAG1*AMP(34)-IMAG1*AMP(39)+IMAG1
     $ *AMP(37)-IMAG1*AMP(42)-IMAG1*AMP(41))
      JAMP(10,1)=+2D0*(-IMAG1*AMP(1)-IMAG1*AMP(3)-IMAG1*AMP(4)+IMAG1
     $ *AMP(6)+IMAG1*AMP(8)-IMAG1*AMP(9)+IMAG1*AMP(11)+IMAG1*AMP(12)
     $ +IMAG1*AMP(27)+IMAG1*AMP(30)+IMAG1*AMP(29)-IMAG1*AMP(36)+IMAG1
     $ *AMP(34)+IMAG1*AMP(39)-IMAG1*AMP(37))
      JAMP(11,1)=+2D0*(-IMAG1*AMP(7)-IMAG1*AMP(8)-IMAG1*AMP(11)-IMAG1
     $ *AMP(10)-IMAG1*AMP(14)+IMAG1*AMP(15)-IMAG1*AMP(17)-IMAG1*AMP(18)
     $ -IMAG1*AMP(26)-IMAG1*AMP(32)-IMAG1*AMP(31)-IMAG1*AMP(39)-IMAG1
     $ *AMP(38)-IMAG1*AMP(42)+IMAG1*AMP(40))
      JAMP(12,1)=+2D0*(-IMAG1*AMP(2)+IMAG1*AMP(3)-IMAG1*AMP(5)-IMAG1
     $ *AMP(6)+IMAG1*AMP(7)+IMAG1*AMP(9)+IMAG1*AMP(10)-IMAG1*AMP(12)
     $ +IMAG1*AMP(26)-IMAG1*AMP(30)-IMAG1*AMP(29)-IMAG1*AMP(33)+IMAG1
     $ *AMP(31)+IMAG1*AMP(42)-IMAG1*AMP(40))
      JAMP(13,1)=+2D0*(+IMAG1*AMP(13)+IMAG1*AMP(15)+IMAG1*AMP(16)
     $ -IMAG1*AMP(18)+IMAG1*AMP(19)+IMAG1*AMP(20)+IMAG1*AMP(23)+IMAG1
     $ *AMP(22)-IMAG1*AMP(26)-IMAG1*AMP(32)-IMAG1*AMP(31)+IMAG1*AMP(41)
     $ +IMAG1*AMP(40)+IMAG1*AMP(45)+IMAG1*AMP(44))
      JAMP(14,1)=+2D0*(+IMAG1*AMP(7)+IMAG1*AMP(8)+IMAG1*AMP(11)+IMAG1
     $ *AMP(10)+IMAG1*AMP(14)-IMAG1*AMP(15)+IMAG1*AMP(17)+IMAG1*AMP(18)
     $ +IMAG1*AMP(26)+IMAG1*AMP(32)+IMAG1*AMP(31)+IMAG1*AMP(39)+IMAG1
     $ *AMP(38)+IMAG1*AMP(42)-IMAG1*AMP(40))
      JAMP(15,1)=+2D0*(-IMAG1*AMP(13)-IMAG1*AMP(14)-IMAG1*AMP(17)
     $ -IMAG1*AMP(16)-IMAG1*AMP(19)-IMAG1*AMP(21)-IMAG1*AMP(22)+IMAG1
     $ *AMP(24)+IMAG1*AMP(27)+IMAG1*AMP(35)+IMAG1*AMP(34)-IMAG1*AMP(38)
     $ -IMAG1*AMP(37)-IMAG1*AMP(45)-IMAG1*AMP(44))
      JAMP(16,1)=+2D0*(+IMAG1*AMP(1)+IMAG1*AMP(2)+IMAG1*AMP(5)+IMAG1
     $ *AMP(4)+IMAG1*AMP(14)-IMAG1*AMP(15)+IMAG1*AMP(17)+IMAG1*AMP(18)
     $ -IMAG1*AMP(27)+IMAG1*AMP(33)+IMAG1*AMP(32)+IMAG1*AMP(36)-IMAG1
     $ *AMP(34)+IMAG1*AMP(38)+IMAG1*AMP(37))
      JAMP(17,1)=+2D0*(-IMAG1*AMP(8)+IMAG1*AMP(9)-IMAG1*AMP(11)-IMAG1
     $ *AMP(12)-IMAG1*AMP(13)-IMAG1*AMP(14)-IMAG1*AMP(17)-IMAG1*AMP(16)
     $ -IMAG1*AMP(25)-IMAG1*AMP(29)-IMAG1*AMP(28)-IMAG1*AMP(39)-IMAG1
     $ *AMP(38)-IMAG1*AMP(45)+IMAG1*AMP(43))
      JAMP(18,1)=+2D0*(-IMAG1*AMP(2)+IMAG1*AMP(3)-IMAG1*AMP(5)-IMAG1
     $ *AMP(6)+IMAG1*AMP(13)+IMAG1*AMP(15)+IMAG1*AMP(16)-IMAG1*AMP(18)
     $ +IMAG1*AMP(25)-IMAG1*AMP(30)+IMAG1*AMP(28)-IMAG1*AMP(33)-IMAG1
     $ *AMP(32)+IMAG1*AMP(45)-IMAG1*AMP(43))
      JAMP(19,1)=+2D0*(+IMAG1*AMP(13)+IMAG1*AMP(14)+IMAG1*AMP(17)
     $ +IMAG1*AMP(16)+IMAG1*AMP(19)+IMAG1*AMP(21)+IMAG1*AMP(22)-IMAG1
     $ *AMP(24)-IMAG1*AMP(27)-IMAG1*AMP(35)-IMAG1*AMP(34)+IMAG1*AMP(38)
     $ +IMAG1*AMP(37)+IMAG1*AMP(45)+IMAG1*AMP(44))
      JAMP(20,1)=+2D0*(+IMAG1*AMP(7)+IMAG1*AMP(8)+IMAG1*AMP(11)+IMAG1
     $ *AMP(10)+IMAG1*AMP(20)-IMAG1*AMP(21)+IMAG1*AMP(23)+IMAG1*AMP(24)
     $ +IMAG1*AMP(27)+IMAG1*AMP(35)+IMAG1*AMP(34)+IMAG1*AMP(39)-IMAG1
     $ *AMP(37)+IMAG1*AMP(42)+IMAG1*AMP(41))
      JAMP(21,1)=+2D0*(-IMAG1*AMP(13)-IMAG1*AMP(15)-IMAG1*AMP(16)
     $ +IMAG1*AMP(18)-IMAG1*AMP(19)-IMAG1*AMP(20)-IMAG1*AMP(23)-IMAG1
     $ *AMP(22)+IMAG1*AMP(26)+IMAG1*AMP(32)+IMAG1*AMP(31)-IMAG1*AMP(41)
     $ -IMAG1*AMP(40)-IMAG1*AMP(45)-IMAG1*AMP(44))
      JAMP(22,1)=+2D0*(+IMAG1*AMP(1)+IMAG1*AMP(2)+IMAG1*AMP(5)+IMAG1
     $ *AMP(4)+IMAG1*AMP(20)-IMAG1*AMP(21)+IMAG1*AMP(23)+IMAG1*AMP(24)
     $ -IMAG1*AMP(26)+IMAG1*AMP(33)-IMAG1*AMP(31)+IMAG1*AMP(36)+IMAG1
     $ *AMP(35)+IMAG1*AMP(41)+IMAG1*AMP(40))
      JAMP(23,1)=+2D0*(-IMAG1*AMP(7)-IMAG1*AMP(9)-IMAG1*AMP(10)+IMAG1
     $ *AMP(12)-IMAG1*AMP(19)-IMAG1*AMP(20)-IMAG1*AMP(23)-IMAG1*AMP(22)
     $ +IMAG1*AMP(25)+IMAG1*AMP(29)+IMAG1*AMP(28)-IMAG1*AMP(42)-IMAG1
     $ *AMP(41)-IMAG1*AMP(44)-IMAG1*AMP(43))
      JAMP(24,1)=+2D0*(-IMAG1*AMP(1)-IMAG1*AMP(3)-IMAG1*AMP(4)+IMAG1
     $ *AMP(6)+IMAG1*AMP(19)+IMAG1*AMP(21)+IMAG1*AMP(22)-IMAG1*AMP(24)
     $ -IMAG1*AMP(25)+IMAG1*AMP(30)-IMAG1*AMP(28)-IMAG1*AMP(36)-IMAG1
     $ *AMP(35)+IMAG1*AMP(44)+IMAG1*AMP(43))

      MATRIX1 = 0.D0
      DO M = 1, NAMPSO
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX1(M,N))) THEN
              MATRIX1 = MATRIX1 + ZTEMP*DCONJG(JAMP(I,N))/DENOM(I)
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(5)=AMP2(5)+AMP(7)*DCONJG(AMP(7))
      AMP2(6)=AMP2(6)+AMP(8)*DCONJG(AMP(8))
      AMP2(7)=AMP2(7)+AMP(9)*DCONJG(AMP(9))
      AMP2(9)=AMP2(9)+AMP(13)*DCONJG(AMP(13))
      AMP2(10)=AMP2(10)+AMP(14)*DCONJG(AMP(14))
      AMP2(11)=AMP2(11)+AMP(15)*DCONJG(AMP(15))
      AMP2(13)=AMP2(13)+AMP(19)*DCONJG(AMP(19))
      AMP2(14)=AMP2(14)+AMP(20)*DCONJG(AMP(20))
      AMP2(15)=AMP2(15)+AMP(21)*DCONJG(AMP(21))
      AMP2(17)=AMP2(17)+AMP(25)*DCONJG(AMP(25))
      AMP2(18)=AMP2(18)+AMP(26)*DCONJG(AMP(26))
      AMP2(19)=AMP2(19)+AMP(27)*DCONJG(AMP(27))
      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX1(M,N))) THEN
              JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      END

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)+AMPSPLITORDERS(ORDERI
     $NDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_SQUARED_ORDERS_FOR_SOIN'
     $ //'DEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

