      DOUBLE PRECISION FUNCTION DSIG4(PP,WGT,IMODE)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.3.2, 2018-06-22
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: g u~ > c u~ c~ WEIGHTED<=3 @1
C     Process: g u~ > s u~ s~ WEIGHTED<=3 @1
C     Process: g u~ > d u~ d~ WEIGHTED<=3 @1
C     Process: g u~ > b u~ b~ WEIGHTED<=3 @1
C     Process: g c~ > u c~ u~ WEIGHTED<=3 @1
C     Process: g c~ > s c~ s~ WEIGHTED<=3 @1
C     Process: g c~ > d c~ d~ WEIGHTED<=3 @1
C     Process: g c~ > b c~ b~ WEIGHTED<=3 @1
C     Process: g s~ > u s~ u~ WEIGHTED<=3 @1
C     Process: g s~ > c s~ c~ WEIGHTED<=3 @1
C     Process: g s~ > d s~ d~ WEIGHTED<=3 @1
C     Process: g s~ > b s~ b~ WEIGHTED<=3 @1
C     Process: g d~ > u d~ u~ WEIGHTED<=3 @1
C     Process: g d~ > c d~ c~ WEIGHTED<=3 @1
C     Process: g d~ > s d~ s~ WEIGHTED<=3 @1
C     Process: g d~ > b d~ b~ WEIGHTED<=3 @1
C     Process: g b~ > u b~ u~ WEIGHTED<=3 @1
C     Process: g b~ > c b~ c~ WEIGHTED<=3 @1
C     Process: g b~ > s b~ s~ WEIGHTED<=3 @1
C     Process: g b~ > d b~ d~ WEIGHTED<=3 @1
C     
C     RETURNS DIFFERENTIAL CROSS SECTION
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     imode 0 run, 1 init, 2 reweight, 
C     3 finalize, 4 only PDFs,
C     5 squared amplitude only (never
C     generate events)
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379.66*1000)  !CONV TO PICOBARNS
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IMODE
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,ITYPE,LP,IPROC
      DOUBLE PRECISION G1
      DOUBLE PRECISION BX2,CX2,SX2,UX2,DX2
      DOUBLE PRECISION XPQ(-7:7),PD(0:MAXPROC)
      DOUBLE PRECISION DSIGUU,R,RCONF
      INTEGER LUN,ICONF,IFACT,NFACT
      DATA NFACT/1/
      SAVE NFACT
C     
C     EXTERNAL FUNCTIONS
C     
      LOGICAL PASSCUTS
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF,CUSTOM_BIAS
      INTEGER NEXTUNOPEN
C     
C     GLOBAL VARIABLES
C     
      INTEGER          IPSEL
      COMMON /SUBPROC/ IPSEL
C     MINCFIG has this config number
      INTEGER           MINCFIG, MAXCFIG
      COMMON/TO_CONFIGS/MINCFIG, MAXCFIG
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED

      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     
C     DATA
C     
      DATA G1/1*1D0/
      DATA BX2,CX2,SX2,UX2,DX2/5*1D0/
C     ----------
C     BEGIN CODE
C     ----------
      DSIG4=0D0

      IF(IMODE.EQ.1)THEN
C       Set up process information from file symfact
        LUN=NEXTUNOPEN()
        NFACT=1
        OPEN(UNIT=LUN,FILE='../symfact.dat',STATUS='OLD',ERR=20)
        DO WHILE(.TRUE.)
          READ(LUN,*,ERR=10,END=10) RCONF, IFACT
          ICONF=INT(RCONF)
          IF(ICONF.EQ.MAPCONFIG(MINCFIG))THEN
            NFACT=IFACT
          ENDIF
        ENDDO
 10     CLOSE(LUN)
        RETURN
 20     WRITE(*,*)'Error opening symfact.dat. No symmetry factor used.'
        RETURN
      ENDIF
C     Continue only if IMODE is 0, 4 or 5
      IF(IMODE.NE.0.AND.IMODE.NE.4.AND.IMODE.NE.5) RETURN


      IF (ABS(LPP(IB(1))).GE.1) THEN
        LP=SIGN(1,LPP(IB(1)))
        G1=PDG2PDF(ABS(LPP(IB(1))),0*LP, 1,XBK(IB(1)),DSQRT(Q2FACT(1)))
      ENDIF
      IF (ABS(LPP(IB(2))).GE.1) THEN
        LP=SIGN(1,LPP(IB(2)))
        BX2=PDG2PDF(ABS(LPP(IB(2))),-5*LP, 1,XBK(IB(2)),DSQRT(Q2FACT(2)
     $   ))
        CX2=PDG2PDF(ABS(LPP(IB(2))),-4*LP, 1,XBK(IB(2)),DSQRT(Q2FACT(2)
     $   ))
        SX2=PDG2PDF(ABS(LPP(IB(2))),-3*LP, 1,XBK(IB(2)),DSQRT(Q2FACT(2)
     $   ))
        UX2=PDG2PDF(ABS(LPP(IB(2))),-2*LP, 1,XBK(IB(2)),DSQRT(Q2FACT(2)
     $   ))
        DX2=PDG2PDF(ABS(LPP(IB(2))),-1*LP, 1,XBK(IB(2)),DSQRT(Q2FACT(2)
     $   ))
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! g u~ > c u~ c~
      PD(IPROC)=G1*UX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g u~ > s u~ s~
      PD(IPROC)=G1*UX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g u~ > d u~ d~
      PD(IPROC)=G1*UX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g u~ > b u~ b~
      PD(IPROC)=G1*UX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g c~ > u c~ u~
      PD(IPROC)=G1*CX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g c~ > s c~ s~
      PD(IPROC)=G1*CX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g c~ > d c~ d~
      PD(IPROC)=G1*CX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g c~ > b c~ b~
      PD(IPROC)=G1*CX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g s~ > u s~ u~
      PD(IPROC)=G1*SX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g s~ > c s~ c~
      PD(IPROC)=G1*SX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g s~ > d s~ d~
      PD(IPROC)=G1*SX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g s~ > b s~ b~
      PD(IPROC)=G1*SX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g d~ > u d~ u~
      PD(IPROC)=G1*DX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g d~ > c d~ c~
      PD(IPROC)=G1*DX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g d~ > s d~ s~
      PD(IPROC)=G1*DX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g d~ > b d~ b~
      PD(IPROC)=G1*DX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g b~ > u b~ u~
      PD(IPROC)=G1*BX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g b~ > c b~ c~
      PD(IPROC)=G1*BX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g b~ > s b~ s~
      PD(IPROC)=G1*BX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IPROC=IPROC+1  ! g b~ > d b~ d~
      PD(IPROC)=G1*BX2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IF (IMODE.EQ.4)THEN
        DSIG4 = PD(0)
        RETURN
      ENDIF
      CALL SMATRIX4(PP,DSIGUU)
      IF (IMODE.EQ.5) THEN
        IF (DSIGUU.LT.1D199) THEN
          DSIG4 = DSIGUU*CONV
        ELSE
          DSIG4 = 0.0D0
        ENDIF
        RETURN
      ENDIF
C     Select a flavor combination (need to do here for right sign)
      CALL RANMAR(R)
      IPSEL=0
      DO WHILE (R.GE.0D0 .AND. IPSEL.LT.IPROC)
        IPSEL=IPSEL+1
        R=R-DABS(PD(IPSEL))/PD(0)
      ENDDO

      DSIGUU=DSIGUU*REWGT(PP)

C     Apply the bias weight specified in the run card (default is 1.0)
      DSIGUU=DSIGUU*CUSTOM_BIAS(PP,DSIGUU,4)

      DSIGUU=DSIGUU*NFACT

      IF (DSIGUU.LT.1D199) THEN
C       Set sign of dsig based on sign of PDF and matrix element
        DSIG4=DSIGN(PD(0)*CONV*DSIGUU,DSIGUU*PD(IPSEL))
      ELSE
        WRITE(*,*) 'Error in matrix element'
        DSIGUU=0D0
        DSIG4=0D0
      ENDIF
C     Generate events only if IMODE is 0.
      IF(IMODE.EQ.0.AND.DABS(DSIG4).GT.0D0)THEN
C       Call UNWGT to unweight and store events
        CALL UNWGT(PP,DSIG4*WGT,4)
      ENDIF

      END
C     
C     Functionality to handling grid
C     



